#:schema https://docs.jj-vcs.dev/latest/config-schema.json
"$schema" = "https://docs.jj-vcs.dev/latest/config-schema.json"

[ui]
default-command = "log"
diff-editor = ":builtin"

[user]
name = "Eduardo Dobay"
email = "edudobay@gmail.com"

[revset-aliases]
"closest_merge(to)" = "heads(::to & merges())"
"closest_bookmark(to)" = "heads(::to & bookmarks())"
"me()" = 'mine() | author_email("edudobay") | author_email("dobay")'

[aliases]

tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]

# `jj l` shows commits on the working-copy commit's (anonymous) bookmark
# compared to the `main` bookmark
l = ["log", "-r", "(trunk()..@):: | (trunk()..@)- | ancestors(trunk(), 10)"]
trunk = ["log", "-r", "ancestors(trunk(), 10)"]
ll = ["log", "-r", "ancestors(@, 10)"]
last = ["show", "@-"]
df = ["diff"]

# `jj stack <revset>` to include specific revs
stack = ["rebase", "--after", "trunk()", "--before", "closest_merge(@)", "--revision"]

# `jj stage` to include the whole stack after the megamerge
stage = ["stack", "closest_merge(@).. ~ empty()"]

# `jj restack` to rebase your changes onto `trunk()`
restack = ["rebase", "--onto", "trunk()", "--source", "roots(trunk()..) & mutable()"]

# https://www.visualjj.com/docs/configuration
[visualjj]
snapshot-enabled = false
auto-init = false
