" local vimrc file
" Maintainer:   Eduardo Dobay

if has('nvim')
  let g:python_host_prog  = stdpath('data') . '/venv-py2/bin/python'
  let g:python3_host_prog = stdpath('data') . '/venv-py3/bin/python'
endif

let g:ctermcolor = 'one|dark'
let g:airline_theme = 'onedark'

let s:plug_path = stdpath('data') . '/site/autoload/plug.vim'

if !filereadable(s:plug_path)
  silent exec "!curl -fLo " . s:plug_path . " --create-dirs "
    \ . "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  autocmd VimEnter * PlugInstall --sync | source ~/dotfiles/vimrc
endif

source ~/dotfiles/vim/plugins.vim
source ~/dotfiles/vim/vim_compat.vim

set hidden
set nobackup

" Enable reading of modelines
set modeline

set expandtab
set smarttab
set autoindent
set smartindent
set shiftwidth=4
set tabstop=4

" always show a status line, even with only one window
set laststatus=2

set showcmd

set wildmode=full
set wildmenu
set wildcharm=<C-Z>
set wildignorecase

set ignorecase
set smartcase
set incsearch
set hlsearch
nohl

set number
set relativenumber
set linebreak
" let &showbreak=' '
set scrolloff=1
set display+=lastline

" Pretty 'list' mode
set listchars=eol:¬,tab:→\ ,trail:·,extends:»,precedes:«,nbsp:⍽

set nrformats-=octal

" Remove extra comment delimiters when joining lines
set formatoptions+=j

set ttimeout
set ttimeoutlen=50

" Open buffers with no folds closed
" See: http://vim.wikia.com/wiki/All_folds_open_when_opening_a_file
set foldlevelstart=99

" Highlight trailing whitespace
match ErrorMsg '\s\+$'

source ~/dotfiles/vim/keys.vim
source ~/dotfiles/vim/keymap.vim

source ~/dotfiles/vim/functions.vim

au WinLeave * call CursorLCHighlight(0)
au WinEnter * call CursorLCHighlight(1)

filetype plugin on

let g:tex_flavor = 'latex'

if !has("gui_running")
   set mouse=a
   if exists("$XTERM_SHELL") || exists("$COLORTERM") || stridx($TERM, "-256color") > 0
      "set t_Co=256
      call LoadColorTheme(g:ctermcolor)
   endif
endif

if has('termguicolors')
   set termguicolors
endif
